import { ChildProps } from '@/types'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { FC } from 'react'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const montserrat = Montserrat({
	weight: ['400', '500', '600', '700', '800', '900'],
	subsets: ['latin'],
})

const RootLayout: FC<ChildProps> = ({ children }) => {
	return (
		<html lang='en'>
			<body className={`${montserrat.className} bg-dark-2 antialiased`}>
				<main>{children}</main>
			</body>
		</html>
	)
}

export default RootLayout
